"""Configuration and Record Definitions for Incident Detection Engine.

================================================================================
DISCLAIMER:
All incident classifications generated by this engine are PROTOTYPE HEURISTIC
ESTIMATIONS — rule-based detections, NOT forensic or legal determinations.
================================================================================
"""

from dataclasses import dataclass, field, asdict
from typing import Dict, Any, List, Optional, Union
from enum import Enum


class IncidentType(str, Enum):
    """Supported prototype incident types."""
    SUSPECTED_HIT_AND_RUN = "SUSPECTED_HIT_AND_RUN"
    RASH_DRIVING = "RASH_DRIVING"


class IncidentSeverity(str, Enum):
    """Incident severity classification levels."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class IncidentStatus(str, Enum):
    """Lifecycle status of an incident record."""
    NEW = "NEW"
    UNDER_REVIEW = "UNDER_REVIEW"
    CONFIRMED = "CONFIRMED"
    DISMISSED = "DISMISSED"


DISCLAIMER_TEXT = (
    "prototype heuristic estimation — rule-based detection, not forensic determination"
)


@dataclass
class IncidentConfig:
    """Centralized configuration thresholds for all rule-based heuristic evaluations.
    
    All tunable spatial, temporal, and kinematic parameters are managed here in a
    single location.
    """
    # General Tracking & Temporal Parameters
    min_track_history_frames: int = 8           # Minimum observed trajectory points before rule evaluation
    cooldown_frames_per_track: int = 60         # Minimum frames between repeated incident triggers for same vehicle
    frame_rate_fps: float = 30.0                # Baseline video FPS for derivative velocity/acceleration calculations
    
    # RASH_DRIVING Heuristic Thresholds (Normalized to 1280x720 baseline)
    # 1. Extreme velocity thresholds
    rash_speed_threshold_px_s: float = 520.0     # Peak normalized speed for reckless speeding
    rash_avg_speed_threshold_px_s: float = 350.0 # Sustained normalized speed for reckless driving
    # 2. Extreme acceleration / jerk
    rash_accel_threshold_px_s2: float = 400.0    # Normalized px/s^2 threshold on smoothed velocity
    # 3. Lateral weaving / aggressive slalom (zero-crossings in detrended lateral displacement)
    rash_min_zero_crossings: int = 2             # Minimum direction reversals across path
    rash_min_lateral_std_px: float = 14.0        # Minimum lateral standard deviation
    rash_min_lateral_speed_px_s: float = 140.0   # Minimum lateral speed during swerve
    # 4. Trajectory curvature / angular swerve threshold (in degrees)
    rash_max_heading_change_deg: float = 35.0    # Sharp sudden turn/swerve angle between movement vectors
    # 5. Event confidence threshold
    rash_min_event_confidence: float = 0.70
    
    # SUSPECTED_HIT_AND_RUN Heuristic Thresholds (Normalized to 1280x720 baseline)
    # 1. Direct physical contact / severe overlap
    hit_and_run_proximity_distance_px: float = 35.0   # Max centroid distance considered direct collision
    hit_and_run_min_iou_overlap: float = 0.15        # Minimum bounding box IoU indicating physical contact
    # 2. Post-encounter rapid flight / speed surge
    hit_and_run_speed_surge_ratio: float = 1.80      # Post-encounter speed must be >= 1.8x pre-encounter velocity
    hit_and_run_min_departure_speed_px_s: float = 350.0 # Must depart at high speed (>= 350 norm-px/s)
    # 3. Post-encounter rapid departure frames window
    hit_and_run_observation_window_frames: int = 30  # Window to observe departure after encounter
    # 4. Abrupt track loss / boundary departure threshold
    hit_and_run_boundary_margin_px: int = 60         # Distance to frame edge considered an active boundary exit
    # 5. Event confidence threshold
    hit_and_run_min_event_confidence: float = 0.75


@dataclass
class IncidentRecord:
    """Standardized record for an AI-detected traffic incident event."""
    incident_id: str
    incident_type: str
    vehicle_tracking_id: int
    registration_number: Optional[str]
    registration_confidence: float
    event_confidence: float
    bus_id: str
    timestamp: str  # ISO-8601 UTC timestamp from GPSVideoSynchronizer
    latitude: float
    longitude: float
    severity: str
    evidence_image: Optional[str] = None
    status: str = "NEW"  # Default status: NEW
    speed_kmh: float = 0.0
    heading_deg: float = 0.0
    frame_number: int = 0
    video_timestamp: float = 0.0
    disclaimer: str = DISCLAIMER_TEXT
    details: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Converts dataclass to serializable dictionary."""
        return asdict(self)
