"""Incident Detection Engine for BusSense-AI.

================================================================================
DISCLAIMER:
All incident detection and classification events generated by this engine are
PROTOTYPE HEURISTIC ESTIMATIONS — rule-based detections, NOT forensic or legal
determinations.
================================================================================
"""

import os
import sys
import time
import logging
from pathlib import Path
from typing import List, Dict, Any, Optional, Union, Tuple, Set
from collections import defaultdict, deque
import numpy as np
import cv2
import json

from ai.pipeline.gps_sync import GPSVideoSynchronizer
from ai.tracking.tracker import VehicleTracker, FrameTrackingResult, TrackedVehicleDetection
from ai.anpr.plate_detector import PlateDetector, PlateDetection
from ai.anpr.ocr_engine import OCREngine, PlateOCRResult
from ai.anpr.validator import PlateValidator, ValidationResult
from ai.anpr.pipeline import PlateIncidentRecord
from ai.incident_detection.config import (
    IncidentConfig,
    IncidentRecord,
    IncidentType,
    IncidentSeverity,
    IncidentStatus,
    DISCLAIMER_TEXT,
)
from ai.incident_detection.rules.base import BaseIncidentRule, IncidentCandidate
from ai.incident_detection.rules.rash_driving import RashDrivingRule
from ai.incident_detection.rules.hit_and_run import HitAndRunRule

logger = logging.getLogger(__name__)

SEVERITY_COLORS = {
    "LOW": (34, 197, 94),          # Green
    "MEDIUM": (0, 165, 255),       # Orange
    "HIGH": (30, 30, 220),         # Red
    "CRITICAL": (214, 39, 40),     # Dark Red / Crimson
}

INCIDENT_BADGE_COLORS = {
    "RASH_DRIVING": (0, 140, 255),          # Amber-Orange
    "SUSPECTED_HIT_AND_RUN": (0, 0, 220),   # Bright Red
}


class IncidentDetector:
    """End-to-end edge AI Incident Detection Engine combining tracking, ANPR, GPS, and heuristic rules."""

    def __init__(
        self,
        config: Optional[IncidentConfig] = None,
        vehicle_model: Union[str, Path] = "yolov8n.pt",
        plate_model: Union[str, Path] = "models/number_plates/best.pt",
        conf_threshold: float = 0.25,
        rules: Optional[List[BaseIncidentRule]] = None,
        bus_id: str = "BUS_101",
        device: str = "cpu",
        imgsz: int = 640,
        enable_ocr: bool = False,
        ocr_languages: Optional[List[str]] = None,
    ):
        """Initializes the IncidentDetector engine.

        Args:
            config: Configuration thresholds instance (or default IncidentConfig).
            vehicle_model: Path or identifier for vehicle detection model.
            plate_model: Path to plate detector weights.
            conf_threshold: Detection confidence threshold.
            rules: List of incident rule strategies (defaults to RashDriving + HitAndRun).
            bus_id: Bus identifier.
            device: Compute device ('cpu', 'cuda', 'mps').
            imgsz: Input resolution for vehicle detection inference.
            enable_ocr: Flag to enable/disable EasyOCR plate extraction.
            ocr_languages: Languages for EasyOCR.
        """
        self.config = config or IncidentConfig()
        self.bus_id = bus_id
        self.conf_threshold = conf_threshold
        self.device = device
        self.imgsz = imgsz
        self.enable_ocr = enable_ocr

        logger.info("Initializing Incident Detection Engine Vehicle Tracker...")
        self.tracker = VehicleTracker(
            model_path=vehicle_model,
            conf_threshold=conf_threshold,
            device=device,
            imgsz=imgsz,
        )

        if self.enable_ocr:
            logger.info("Initializing ANPR Plate Detector and OCR Engine...")
            self.plate_detector = PlateDetector(
                custom_weights_path=plate_model,
                conf_threshold=conf_threshold,
                device=device,
            )
            self.ocr_engine = OCREngine(
                languages=ocr_languages or ["en"],
                gpu=False,
                min_confidence=0.20,
            )
            self.validator = PlateValidator()
        else:
            self.plate_detector = None
            self.ocr_engine = None
            self.validator = None

        # Pluggable Incident Rules
        self.rules: List[BaseIncidentRule] = rules if rules is not None else [
            RashDrivingRule(),
            HitAndRunRule(),
        ]

        self.reset_state()

    def reset_state(self) -> None:
        """Resets tracking histories, incident caches, and cooldown counters."""
        self.tracker.reset_state()
        
        # Per-track kinematic history:
        # track_id -> {
        #   'centroids': deque([(cx, cy), ...]),
        #   'timestamps': deque([t0, ...]),
        #   'boxes': deque([[x1, y1, x2, y2], ...]),
        #   'velocities': deque([v0, ...]),
        #   'vehicle_type': str,
        #   'last_seen_frame': int
        # }
        self.track_states: Dict[int, Dict[str, Any]] = defaultdict(lambda: {
            "centroids": deque(maxlen=45),
            "timestamps": deque(maxlen=45),
            "boxes": deque(maxlen=45),
            "velocities": deque(maxlen=45),
            "vehicle_type": "car",
            "last_seen_frame": 0,
        })

        # Cache of best recognized plate per track: track_id -> (plate_str, conf)
        self.best_plates: Dict[int, Tuple[str, float]] = {}

        # Cooldown management: (track_id, incident_type) -> last_triggered_frame
        self.incident_cooldowns: Dict[Tuple[int, str], int] = {}

        # Incident history log
        self.all_incidents: List[IncidentRecord] = []
        self._incident_seq = 1

    def add_rule(self, rule: BaseIncidentRule) -> None:
        """Registers an additional incident detection rule."""
        self.rules.append(rule)

    def process_frame(
        self,
        frame: np.ndarray,
        frame_number: int = 0,
        video_timestamp: float = 0.0,
        gps_synchronizer: Optional[GPSVideoSynchronizer] = None,
        output_evidence_dir: Optional[Union[str, Path]] = None,
    ) -> Tuple[FrameTrackingResult, List[IncidentRecord]]:
        """Processes a single video frame, tracks vehicles, updates kinematics,
        evaluates incident rules, and synchronizes GPS telemetry.

        Args:
            frame: OpenCV BGR image array.
            frame_number: Frame sequence number.
            video_timestamp: Playback timestamp in seconds.
            gps_synchronizer: Instance of GPSVideoSynchronizer (single source of truth).
            output_evidence_dir: Directory to save generated incident evidence cards.

        Returns:
            Tuple of (FrameTrackingResult, List of new IncidentRecords generated in this frame).
        """
        if frame is None or frame.size == 0:
            raise ValueError("Input frame is invalid or empty.")

        h, w = frame.shape[:2]

        # 1. Track Vehicles via ByteTrack
        track_res = self.tracker.track_frame(
            frame=frame,
            frame_number=frame_number,
            video_timestamp=video_timestamp,
            conf_threshold=self.conf_threshold,
            imgsz=self.imgsz,
        )

        # 2. Resolve GPS Position via GPSVideoSynchronizer
        if gps_synchronizer is not None:
            pos = gps_synchronizer.get_position(video_timestamp=video_timestamp, interpolate=True)
            iso_time = pos.get("gps_timestamp") or pos.get("interpolated_timestamp") or ""
            lat = float(pos.get("latitude", 0.0))
            lon = float(pos.get("longitude", 0.0))
            spd = float(pos.get("speed", 0.0))
            hdg = float(pos.get("heading", 0.0))
        else:
            iso_time = "2026-09-09T00:00:00Z"
            lat, lon, spd, hdg = 17.385044, 78.486671, 0.0, 0.0

        # 3. Update ANPR & Kinematics for Active Tracks
        current_detections = track_res.detections
        active_track_ids: Set[int] = set()

        for det in current_detections:
            t_id = det.track_id
            v_type = det.vehicle_type
            v_box = det.bounding_box
            cx, cy = det.centroid
            active_track_ids.add(t_id)

            t_state = self.track_states[t_id]
            t_state["centroids"].append((cx, cy))
            t_state["timestamps"].append(video_timestamp)
            t_state["boxes"].append(v_box)
            t_state["vehicle_type"] = v_type
            t_state["last_seen_frame"] = frame_number

            # Calculate instantaneous velocity if prior point exists
            if len(t_state["centroids"]) >= 2:
                prev_cx, prev_cy = t_state["centroids"][-2]
                prev_t = t_state["timestamps"][-2]
                dt = max(0.001, video_timestamp - prev_t)
                dist_px = np.sqrt((cx - prev_cx) ** 2 + (cy - prev_cy) ** 2)
                vel_px_s = float(dist_px / dt)
                t_state["velocities"].append(vel_px_s)

            # Perform ANPR extraction if enabled, vehicle is close enough, and plate not yet confirmed
            if self.enable_ocr and self.plate_detector is not None and self.ocr_engine is not None:
                current_plate_conf = self.best_plates.get(t_id, ("", 0.0))[1]
                v_w = v_box[2] - v_box[0]
                v_h = v_box[3] - v_box[1]
                res_scale = max(0.2, min(w, h * 16 // 9) / 1280.0)
                norm_w = v_w / res_scale
                norm_h = v_h / res_scale

                if norm_w >= 80 and norm_h >= 50 and current_plate_conf < 0.80 and (frame_number % 6 == 0 or t_id not in self.best_plates):
                    plate_det = self.plate_detector.detect_plate_in_vehicle(
                        frame=frame,
                        vehicle_box=v_box,
                        vehicle_type=v_type,
                    )
                    if plate_det is not None and plate_det.plate_crop.size > 0:
                        ocr_res = self.ocr_engine.recognize_text(plate_det.plate_crop)
                        if ocr_res.raw_text:
                            val_res = self.validator.validate_and_normalize(ocr_res.raw_text)
                            if val_res.normalized_text and ocr_res.confidence > current_plate_conf:
                                self.best_plates[t_id] = (val_res.normalized_text, ocr_res.confidence)

        # 4. Evaluate Incident Rules on Active Tracks
        frame_meta = {
            "frame_number": frame_number,
            "video_timestamp": video_timestamp,
            "width": w,
            "height": h,
            "fps": self.config.frame_rate_fps,
        }

        # Format serializable snapshot of all track states for cross-vehicle rules
        all_tracks_snapshot: Dict[int, Dict[str, Any]] = {}
        for trk_id, st in self.track_states.items():
            all_tracks_snapshot[trk_id] = {
                "centroids": list(st["centroids"]),
                "timestamps": list(st["timestamps"]),
                "boxes": list(st["boxes"]),
                "velocities": list(st["velocities"]),
                "vehicle_type": st["vehicle_type"],
                "last_seen_frame": st["last_seen_frame"],
            }

        new_incidents: List[IncidentRecord] = []

        for t_id in active_track_ids:
            t_state = all_tracks_snapshot[t_id]
            
            for rule in self.rules:
                candidate: Optional[IncidentCandidate] = rule.evaluate(
                    track_id=t_id,
                    track_state=t_state,
                    all_tracks_state=all_tracks_snapshot,
                    frame_meta=frame_meta,
                    config=self.config,
                )

                if candidate is not None:
                    incident_type_str = candidate.incident_type.value
                    cooldown_key = (t_id, incident_type_str)
                    last_fired = self.incident_cooldowns.get(cooldown_key, -999)

                    # Check cooldown
                    if (frame_number - last_fired) >= self.config.cooldown_frames_per_track:
                        self.incident_cooldowns[cooldown_key] = frame_number
                        
                        reg_num, reg_conf = self.best_plates.get(t_id, (None, 0.0))
                        incident_id = f"inc_{self.bus_id}_{incident_type_str.lower()}_{t_id:04d}_{frame_number:06d}"

                        # Generate Evidence Image Card if directory provided
                        evidence_file_path = None
                        if output_evidence_dir is not None:
                            out_dir = Path(output_evidence_dir)
                            out_dir.mkdir(parents=True, exist_ok=True)
                            fname = f"incident_{self.bus_id}_{incident_type_str}_{t_id:04d}_{frame_number:06d}.jpg"
                            target_evidence = out_dir / fname

                            # Extract vehicle crop
                            box = t_state["boxes"][-1] if t_state["boxes"] else [0, 0, w, h]
                            vx1, vy1, vx2, vy2 = [max(0, int(b)) for b in box]
                            vx2 = min(w, vx2)
                            vy2 = min(h, vy2)
                            veh_crop = frame[vy1:vy2, vx1:vx2] if vy2 > vy1 and vx2 > vx1 else None

                            card_img = self.create_evidence_image(
                                frame=frame,
                                candidate=candidate,
                                track_id=t_id,
                                vehicle_type=t_state["vehicle_type"],
                                vehicle_box=box,
                                vehicle_crop=veh_crop,
                                reg_num=reg_num,
                                reg_conf=reg_conf,
                                timestamp_str=iso_time,
                                lat=lat,
                                lon=lon,
                                speed_kmh=spd,
                                heading_deg=hdg,
                                frame_number=frame_number,
                            )
                            cv2.imwrite(str(target_evidence), card_img)
                            evidence_file_path = str(target_evidence)

                        rec = IncidentRecord(
                            incident_id=incident_id,
                            incident_type=incident_type_str,
                            vehicle_tracking_id=t_id,
                            registration_number=reg_num,
                            registration_confidence=round(float(reg_conf), 3),
                            event_confidence=round(float(candidate.event_confidence), 3),
                            bus_id=self.bus_id,
                            timestamp=iso_time,
                            latitude=round(lat, 6),
                            longitude=round(lon, 6),
                            severity=candidate.severity.value,
                            evidence_image=evidence_file_path,
                            status=IncidentStatus.NEW.value,
                            speed_kmh=round(spd, 2),
                            heading_deg=round(hdg, 1),
                            frame_number=frame_number,
                            video_timestamp=round(video_timestamp, 3),
                            disclaimer=DISCLAIMER_TEXT,
                            details=candidate.details,
                        )
                        new_incidents.append(rec)
                        self.all_incidents.append(rec)
                        self._incident_seq += 1

        return track_res, new_incidents

    def create_evidence_image(
        self,
        frame: np.ndarray,
        candidate: IncidentCandidate,
        track_id: int,
        vehicle_type: str,
        vehicle_box: List[int],
        vehicle_crop: Optional[np.ndarray],
        reg_num: Optional[str],
        reg_conf: float,
        timestamp_str: str,
        lat: float,
        lon: float,
        speed_kmh: float,
        heading_deg: float,
        frame_number: int,
    ) -> np.ndarray:
        """Creates a composite tri-panel diagnostic evidence card for the detected incident.

        Layout (1280x720):
        ┌─────────────────────────┬─────────────────────────┬─────────────────────────┐
        │  1. Scene Context       │  2. Target Vehicle      │  3. Telemetry &         │
        │     with Highlighted    │     & Number Plate      │     Rule Diagnostics    │
        │     Trajectory Trail    │     Close-up Crop       │     (with Disclaimer)   │
        └─────────────────────────┴─────────────────────────┴─────────────────────────┘
        """
        card_w, card_h = 1280, 720
        card = np.zeros((card_h, card_w, 3), dtype=np.uint8)
        card[:] = (18, 18, 22)  # Dark slate background

        # Header Title Bar
        sev_color = SEVERITY_COLORS.get(candidate.severity.value, (0, 165, 255))
        cv2.rectangle(card, (0, 0), (card_w, 70), (28, 30, 36), -1)
        cv2.line(card, (0, 70), (card_w, 70), sev_color, 3)

        title_text = f"INCIDENT EVIDENCE: {candidate.incident_type.value} [{candidate.severity.value}]"
        cv2.putText(card, title_text, (24, 45), cv2.FONT_HERSHEY_DUPLEX, 1.0, (255, 255, 255), 2, cv2.LINE_AA)
        
        bus_badge = f"BUS: {self.bus_id} | FRAME: {frame_number:06d}"
        cv2.putText(card, bus_badge, (card_w - 380, 45), cv2.FONT_HERSHEY_SIMPLEX, 0.70, (200, 200, 200), 2, cv2.LINE_AA)

        # Panel 1: Scene Context (Left Panel, 460x520)
        panel1_x, panel1_y, panel1_w, panel1_h = 24, 90, 460, 520
        cv2.rectangle(card, (panel1_x, panel1_y), (panel1_x + panel1_w, panel1_y + panel1_h), (40, 44, 52), -1)
        cv2.rectangle(card, (panel1_x, panel1_y), (panel1_x + panel1_w, panel1_y + panel1_h), (70, 75, 85), 2)

        scene_annotated = frame.copy()
        vx1, vy1, vx2, vy2 = vehicle_box
        cv2.rectangle(scene_annotated, (vx1, vy1), (vx2, vy2), sev_color, 4)
        
        # Draw motion trail on scene context
        t_state = self.track_states.get(track_id)
        if t_state and len(t_state["centroids"]) >= 2:
            pts = list(t_state["centroids"])
            for idx in range(1, len(pts)):
                cv2.line(scene_annotated, pts[idx - 1], pts[idx], (0, 255, 255), 3, cv2.LINE_AA)

        # Scale scene into panel 1
        scene_resized = cv2.resize(scene_annotated, (panel1_w - 16, panel1_h - 60))
        card[panel1_y + 46 : panel1_y + 46 + scene_resized.shape[0], panel1_x + 8 : panel1_x + 8 + scene_resized.shape[1]] = scene_resized
        cv2.putText(card, "1. SCENE CONTEXT & TRAJECTORY", (panel1_x + 12, panel1_y + 30), cv2.FONT_HERSHEY_SIMPLEX, 0.65, (255, 255, 255), 2, cv2.LINE_AA)

        # Panel 2: Target Vehicle & Plate (Center Panel, 350x520)
        panel2_x, panel2_y, panel2_w, panel2_h = 508, 90, 350, 520
        cv2.rectangle(card, (panel2_x, panel2_y), (panel2_x + panel2_w, panel2_y + panel2_h), (40, 44, 52), -1)
        cv2.rectangle(card, (panel2_x, panel2_y), (panel2_x + panel2_w, panel2_y + panel2_h), (70, 75, 85), 2)
        cv2.putText(card, "2. TARGET VEHICLE", (panel2_x + 12, panel2_y + 30), cv2.FONT_HERSHEY_SIMPLEX, 0.65, (255, 255, 255), 2, cv2.LINE_AA)

        if vehicle_crop is not None and vehicle_crop.size > 0:
            vh, vw = vehicle_crop.shape[:2]
            scale = min((panel2_w - 24) / vw, 260 / vh)
            new_vw, new_vh = int(vw * scale), int(vh * scale)
            crop_resized = cv2.resize(vehicle_crop, (new_vw, new_vh))
            start_y = panel2_y + 50 + (260 - new_vh) // 2
            start_x = panel2_x + (panel2_w - new_vw) // 2
            card[start_y : start_y + new_vh, start_x : start_x + new_vw] = crop_resized
            cv2.rectangle(card, (start_x, start_y), (start_x + new_vw, start_y + new_vh), (0, 200, 255), 2)

        # License Plate Banner / Vehicle Identification in Panel 2
        plate_box_y = panel2_y + 340
        cv2.rectangle(card, (panel2_x + 12, plate_box_y), (panel2_x + panel2_w - 12, plate_box_y + 140), (25, 25, 30), -1)
        cv2.rectangle(card, (panel2_x + 12, plate_box_y), (panel2_x + panel2_w - 12, plate_box_y + 140), (255, 200, 0), 2)
        
        if reg_num:
            cv2.putText(card, "RECOGNIZED NUMBER PLATE", (panel2_x + 24, plate_box_y + 30), cv2.FONT_HERSHEY_SIMPLEX, 0.50, (180, 180, 180), 1, cv2.LINE_AA)
            cv2.putText(card, reg_num, (panel2_x + 24, plate_box_y + 75), cv2.FONT_HERSHEY_DUPLEX, 0.90, (0, 255, 120), 2, cv2.LINE_AA)
            conf_str = f"OCR Confidence: {reg_conf * 100:.1f}%"
            cv2.putText(card, conf_str, (panel2_x + 24, plate_box_y + 115), cv2.FONT_HERSHEY_SIMPLEX, 0.55, (200, 200, 200), 1, cv2.LINE_AA)
        else:
            cv2.putText(card, "VEHICLE CLASSIFICATION", (panel2_x + 24, plate_box_y + 30), cv2.FONT_HERSHEY_SIMPLEX, 0.50, (180, 180, 180), 1, cv2.LINE_AA)
            status_text = f"TARGET: #{track_id} {vehicle_type.upper()}"
            cv2.putText(card, status_text, (panel2_x + 24, plate_box_y + 75), cv2.FONT_HERSHEY_DUPLEX, 0.80, (0, 220, 255), 2, cv2.LINE_AA)
            opt_str = "Fast Incident Telemetry Mode" if not self.enable_ocr else "Plate Unresolved / Blurry"
            cv2.putText(card, opt_str, (panel2_x + 24, plate_box_y + 115), cv2.FONT_HERSHEY_SIMPLEX, 0.50, (180, 180, 180), 1, cv2.LINE_AA)

        # Panel 3: Telemetry & Heuristic Diagnostics (Right Panel, 374x520)
        panel3_x, panel3_y, panel3_w, panel3_h = 882, 90, 374, 520
        cv2.rectangle(card, (panel3_x, panel3_y), (panel3_x + panel3_w, panel3_y + panel3_h), (40, 44, 52), -1)
        cv2.rectangle(card, (panel3_x, panel3_y), (panel3_x + panel3_w, panel3_y + panel3_h), (70, 75, 85), 2)
        cv2.putText(card, "3. TELEMETRY & RULE AUDIT", (panel3_x + 12, panel3_y + 30), cv2.FONT_HERSHEY_SIMPLEX, 0.65, (255, 255, 255), 2, cv2.LINE_AA)

        telemetry_lines = [
            ("Track ID:", f"#{track_id} ({vehicle_type.upper()})"),
            ("Event Confidence:", f"{candidate.event_confidence * 100:.1f}%"),
            ("Severity Rating:", candidate.severity.value),
            ("Bus Speed:", f"{speed_kmh:.1f} km/h (Hdg {heading_deg:.0f})"),
            ("GPS Lat / Lon:", f"{lat:.6f}, {lon:.6f}"),
            ("GPS Timestamp:", timestamp_str.replace("T", " ")[:19]),
        ]

        cur_ty = panel3_y + 70
        for label, val in telemetry_lines:
            cv2.putText(card, label, (panel3_x + 16, cur_ty), cv2.FONT_HERSHEY_SIMPLEX, 0.52, (170, 175, 185), 1, cv2.LINE_AA)
            cv2.putText(card, val, (panel3_x + 155, cur_ty), cv2.FONT_HERSHEY_SIMPLEX, 0.52, (255, 255, 255), 1, cv2.LINE_AA)
            cur_ty += 28

        # Diagnostic Indicators
        cv2.line(card, (panel3_x + 16, cur_ty + 5), (panel3_x + panel3_w - 16, cur_ty + 5), (60, 65, 75), 1)
        cur_ty += 28
        cv2.putText(card, "HEURISTIC TRIGGER DETAILS:", (panel3_x + 16, cur_ty), cv2.FONT_HERSHEY_SIMPLEX, 0.52, (255, 200, 0), 1, cv2.LINE_AA)
        cur_ty += 24

        indicators = candidate.details.get("triggered_indicators", [candidate.reasoning])
        for ind in indicators[:4]:
            ind_short = (ind[:38] + "...") if len(ind) > 40 else ind
            cv2.putText(card, f"• {ind_short}", (panel3_x + 16, cur_ty), cv2.FONT_HERSHEY_SIMPLEX, 0.44, (220, 220, 220), 1, cv2.LINE_AA)
            cur_ty += 22

        # Bottom Disclaimer Banner across the full card
        cv2.rectangle(card, (0, 640), (card_w, 720), (14, 14, 18), -1)
        cv2.line(card, (0, 640), (card_w, 640), (60, 65, 75), 1)
        disclaimer_display = f"DISCLAIMER: {DISCLAIMER_TEXT.upper()}."
        cv2.putText(card, disclaimer_display, (24, 680), cv2.FONT_HERSHEY_SIMPLEX, 0.50, (140, 145, 155), 1, cv2.LINE_AA)

        return card

    def annotate_frame(
        self,
        frame: np.ndarray,
        tracking_result: FrameTrackingResult,
        active_incidents: Optional[List[IncidentRecord]] = None,
        fps: float = 0.0,
        show_hud: bool = True,
    ) -> np.ndarray:
        """Annotates video frame with resolution-scaled vehicle tracks, incident badges, and disclaimer HUD banner."""
        annotated = frame.copy()
        h, w = annotated.shape[:2]

        # Resolution scale factor
        res_scale = max(1.0, min(w, h * 16 // 9) / 1280.0)
        box_thick = max(2, int(round(2.2 * res_scale)))
        font_scale = 0.58 * res_scale
        font_thick = max(1, int(round(1.6 * res_scale)))

        # Map active incidents by vehicle_tracking_id
        incidents_by_track: Dict[int, IncidentRecord] = {}
        if active_incidents:
            for inc in active_incidents:
                incidents_by_track[inc.vehicle_tracking_id] = inc

        # 1. Draw Trajectory Trails & Bounding Boxes
        for det in tracking_result.detections:
            t_id = det.track_id
            v_type = det.vehicle_type
            x1, y1, x2, y2 = det.bounding_box
            cx, cy = det.centroid

            # Check if track has an active incident trigger
            inc_rec = incidents_by_track.get(t_id)
            if inc_rec:
                box_color = SEVERITY_COLORS.get(inc_rec.severity, (0, 0, 255))
                badge_bg = INCIDENT_BADGE_COLORS.get(inc_rec.incident_type, (0, 0, 200))
            else:
                box_color = (245, 130, 48) if v_type == "car" else (34, 197, 94)
                badge_bg = (30, 30, 30)

            # Draw trajectory trail
            t_state = self.track_states.get(t_id)
            if t_state and len(t_state["centroids"]) >= 2:
                pts = list(t_state["centroids"])
                trail_color = (0, 0, 255) if inc_rec else (0, 220, 255)
                for idx in range(1, len(pts)):
                    cv2.line(annotated, pts[idx - 1], pts[idx], trail_color, max(2, int(2 * res_scale)), cv2.LINE_AA)

            # Draw vehicle bounding box
            cv2.rectangle(annotated, (x1, y1), (x2, y2), box_color, box_thick)

            # Draw vehicle ID & Class label badge
            reg_num = self.best_plates.get(t_id, (None, 0.0))[0]
            label_core = f"#{t_id} {v_type.upper()}"
            if reg_num:
                label_core += f" [{reg_num}]"

            (tw, th), tb = cv2.getTextSize(label_core, cv2.FONT_HERSHEY_DUPLEX, font_scale, font_thick)
            lbl_y1 = max(0, y1 - th - 10)
            lbl_y2 = y1
            cv2.rectangle(annotated, (x1, lbl_y1), (x1 + tw + 12, lbl_y2), (20, 20, 24), -1)
            cv2.rectangle(annotated, (x1, lbl_y1), (x1 + tw + 12, lbl_y2), box_color, max(1, int(res_scale)))
            cv2.putText(annotated, label_core, (x1 + 6, lbl_y2 - 5), cv2.FONT_HERSHEY_DUPLEX, font_scale, (255, 255, 255), font_thick, cv2.LINE_AA)

            # If incident detected, draw prominent incident alert badge above box
            if inc_rec:
                inc_label = f"ALERT: {inc_rec.incident_type} ({inc_rec.event_confidence * 100:.0f}%)"
                (itw, ith), itb = cv2.getTextSize(inc_label, cv2.FONT_HERSHEY_DUPLEX, font_scale * 1.05, font_thick + 1)
                inc_y1 = max(0, lbl_y1 - ith - 12)
                inc_y2 = lbl_y1 - 2
                cv2.rectangle(annotated, (x1, inc_y1), (x1 + itw + 16, inc_y2), badge_bg, -1)
                cv2.rectangle(annotated, (x1, inc_y1), (x1 + itw + 16, inc_y2), (255, 255, 255), max(1, int(res_scale)))
                cv2.putText(annotated, inc_label, (x1 + 8, inc_y2 - 6), cv2.FONT_HERSHEY_DUPLEX, font_scale * 1.05, (255, 255, 255), font_thick, cv2.LINE_AA)

        # 2. Top HUD Banner with Heuristic Disclaimer
        if show_hud:
            hud_h = int(round(88 * res_scale))
            overlay = annotated.copy()
            cv2.rectangle(overlay, (0, 0), (w, hud_h), (18, 20, 26), -1)
            cv2.addWeighted(overlay, 0.85, annotated, 0.15, 0, annotated)
            cv2.line(annotated, (0, hud_h), (w, hud_h), (220, 40, 40), max(2, int(2 * res_scale)))

            hud_font_scale = 0.58 * res_scale
            hud_font_thick = max(1, int(round(1.5 * res_scale)))

            line1 = f"BusSense-AI Incident Engine | Active Vehicles: {len(tracking_result.detections)} | Total Tracked: {len(self.track_states)} | Incidents: {len(self.all_incidents)}"
            if fps > 0:
                line1 += f" | FPS: {fps:.1f}"

            line2 = f"NOTE: {DISCLAIMER_TEXT.upper()}"

            cv2.putText(annotated, line1, (int(16 * res_scale), int(34 * res_scale)), cv2.FONT_HERSHEY_SIMPLEX, hud_font_scale, (255, 255, 255), hud_font_thick, cv2.LINE_AA)
            cv2.putText(annotated, line2, (int(16 * res_scale), int(68 * res_scale)), cv2.FONT_HERSHEY_SIMPLEX, hud_font_scale * 0.88, (140, 200, 255), hud_font_thick, cv2.LINE_AA)

        return annotated

    def process_video(
        self,
        video_path: Union[str, Path],
        output_video_path: Optional[Union[str, Path]] = None,
        output_json_path: Optional[Union[str, Path]] = None,
        output_evidence_dir: Optional[Union[str, Path]] = None,
        gps_csv_path: Optional[Union[str, Path]] = None,
        max_frames: Optional[int] = None,
    ) -> Dict[str, Any]:
        """Runs end-to-end incident detection on an entire video file.

        Args:
            video_path: Path to input video file.
            output_video_path: Destination path for annotated MP4 video.
            output_json_path: Destination path for structured incident records JSON.
            output_evidence_dir: Directory to save tri-panel evidence cards.
            gps_csv_path: Path to GPS CSV trajectory file.
            max_frames: Optional cap on frames processed.

        Returns:
            Dictionary summary with total frames, vehicle counts, and generated incident records.
        """
        v_path = Path(video_path)
        if not v_path.exists():
            raise FileNotFoundError(f"Input video not found: {v_path}")

        self.reset_state()

        # Initialize GPS Synchronizer if CSV provided
        gps_sync: Optional[GPSVideoSynchronizer] = None
        if gps_csv_path is not None:
            g_path = Path(gps_csv_path)
            if g_path.exists():
                logger.info(f"Initializing GPS Synchronizer from: {g_path}")
                gps_sync = GPSVideoSynchronizer(gps_source=g_path, bus_id=self.bus_id)
            else:
                logger.warning(f"GPS CSV path not found: {g_path}")

        cap = cv2.VideoCapture(str(v_path))
        if not cap.isOpened():
            raise RuntimeError(f"Failed to open video capture: {v_path}")

        fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
        width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        total_video_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        self.config.frame_rate_fps = fps

        writer = None
        if output_video_path is not None:
            out_v = Path(output_video_path)
            out_v.parent.mkdir(parents=True, exist_ok=True)
            fourcc = cv2.VideoWriter_fourcc(*"mp4v")
            writer = cv2.VideoWriter(str(out_v), fourcc, fps, (width, height))

        if output_evidence_dir is not None:
            Path(output_evidence_dir).mkdir(parents=True, exist_ok=True)

        logger.info(f"Processing incident detection on {v_path.name} ({width}x{height} @ {fps:.1f} FPS, {total_video_frames} frames)...")

        frame_idx = 0
        all_detected_incidents: List[IncidentRecord] = []
        t_start = time.time()

        try:
            while True:
                ret, frame = cap.read()
                if not ret or frame is None:
                    break

                video_ts = frame_idx / fps

                # Process frame through incident detection engine
                track_res, new_incidents = self.process_frame(
                    frame=frame,
                    frame_number=frame_idx,
                    video_timestamp=video_ts,
                    gps_synchronizer=gps_sync,
                    output_evidence_dir=output_evidence_dir,
                )

                if new_incidents:
                    all_detected_incidents.extend(new_incidents)
                    for inc in new_incidents:
                        logger.info(f"🚨 [Frame {frame_idx:05d}] {inc.incident_type} (Severity: {inc.severity}, Conf: {inc.event_confidence:.2f}, Trk: #{inc.vehicle_tracking_id}, Plate: {inc.registration_number or 'UNRECOGNIZED'})")

                # Write annotated video frame
                if writer is not None:
                    ann_frame = self.annotate_frame(
                        frame=frame,
                        tracking_result=track_res,
                        active_incidents=new_incidents,
                        fps=fps,
                    )
                    writer.write(ann_frame)

                frame_idx += 1
                if frame_idx % 60 == 0:
                    elapsed = time.time() - t_start
                    cur_fps = frame_idx / max(0.001, elapsed)
                    logger.info(f"Processed {frame_idx}/{total_video_frames} frames ({cur_fps:.1f} FPS) | Incidents: {len(all_detected_incidents)}")

                if max_frames is not None and frame_idx >= max_frames:
                    break

        finally:
            cap.release()
            if writer is not None:
                writer.release()

        elapsed_total = time.time() - t_start
        logger.info(f"Incident detection completed: {frame_idx} frames processed in {elapsed_total:.2f}s ({frame_idx/max(0.001, elapsed_total):.1f} FPS). Total incidents: {len(all_detected_incidents)}")

        # Export structured JSON records
        records_dict = [rec.to_dict() for rec in all_detected_incidents]
        if output_json_path is not None:
            out_j = Path(output_json_path)
            out_j.parent.mkdir(parents=True, exist_ok=True)
            with open(out_j, "w", encoding="utf-8") as f:
                json.dump(records_dict, f, indent=2)
            logger.info(f"Exported {len(records_dict)} incident records to {out_j}")

        return {
            "total_frames_processed": frame_idx,
            "total_incidents_detected": len(all_detected_incidents),
            "incidents_by_type": {
                IncidentType.SUSPECTED_HIT_AND_RUN.value: sum(1 for i in all_detected_incidents if i.incident_type == IncidentType.SUSPECTED_HIT_AND_RUN.value),
                IncidentType.RASH_DRIVING.value: sum(1 for i in all_detected_incidents if i.incident_type == IncidentType.RASH_DRIVING.value),
            },
            "records": records_dict,
        }
